import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — OpenClay",
  description: "OpenClay privacy policy. We don't collect, store, or process your data.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white text-zinc-900">
      <nav className="border-b border-zinc-100 bg-white/80 backdrop-blur-xl">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5">
            <img src="/icon.svg" alt="OpenClay" className="h-8 w-8 rounded-lg" />
            <span className="text-base font-bold tracking-tight">OpenClay</span>
          </Link>
          <Link href="/tool" className="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white transition hover:bg-zinc-800">Open App</Link>
        </div>
      </nav>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-3xl font-bold">Privacy Policy</h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: February 2026</p>

        <div className="mt-10 space-y-8 text-[15px] leading-relaxed text-zinc-600">
          <section>
            <h2 className="text-lg font-semibold text-zinc-900">The short version</h2>
            <p className="mt-2">
              OpenClay does not collect, store, or process any personal data. We have no database, no user accounts,
              no cookies, and no localStorage. Your API keys and spreadsheet data never leave your browser
              except to make direct API calls to your chosen AI provider (Anthropic or Google).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">Data we collect</h2>
            <p className="mt-2">We collect minimal, anonymized usage data. Specifically:</p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5">
              <li>We do not collect personal information</li>
              <li>We do not use cookies or localStorage</li>
              <li>We do not log API requests, API keys, or user data on our servers</li>
              <li>We do not store uploaded files — they are parsed entirely in your browser</li>
              <li>We use <strong className="text-zinc-900">Vercel Web Analytics</strong> to collect anonymous, aggregated page view data (no cookies, no personal data)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">Your API key</h2>
            <p className="mt-2">
              Your API key is stored exclusively in browser memory (React <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-sm">useState()</code>).
              It is never written to localStorage, cookies, or any persistent storage. When you close the tab, it is gone.
              The key is sent directly from your browser to your chosen AI provider&apos;s API — our server acts only as a
              CORS proxy and does not read, log, or store the key.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">Your spreadsheet data</h2>
            <p className="mt-2">
              Files are parsed entirely client-side using JavaScript libraries (PapaParse for CSV, SheetJS for Excel).
              Your data is never uploaded to any server. Enrichment results are generated by the AI provider you connect
              and returned directly to your browser.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">Third-party services</h2>
            <p className="mt-2">
              When you use OpenClay, your data is sent to the AI provider you choose:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5">
              <li><strong className="text-zinc-900">Anthropic (Claude)</strong> — subject to <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" className="text-zinc-900 underline">Anthropic&apos;s Privacy Policy</a></li>
              <li><strong className="text-zinc-900">Google (Gemini)</strong> — subject to <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-zinc-900 underline">Google&apos;s Privacy Policy</a></li>
              <li><strong className="text-zinc-900">Vercel Web Analytics</strong> — collects anonymous page view data without cookies. See <a href="https://vercel.com/docs/analytics/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-zinc-900 underline">Vercel Analytics Privacy</a></li>
            </ul>
            <p className="mt-3">
              This application is hosted on Vercel. Vercel may collect standard server logs (IP address, request timestamp).
              See <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-zinc-900 underline">Vercel&apos;s Privacy Policy</a> for details.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">Open source</h2>
            <p className="mt-2">
              OpenClay is fully open source. You can audit the entire codebase to verify these claims. We believe
              transparency is the strongest privacy guarantee.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">Contact</h2>
            <p className="mt-2">
              Questions about this policy? Reach out via{" "}
              <a href="https://www.linkedin.com/in/-raghav/" target="_blank" rel="noopener noreferrer" className="text-zinc-900 underline">LinkedIn</a>.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-zinc-100 px-6 py-6 text-center text-xs text-zinc-400">
        <div className="mx-auto flex max-w-3xl items-center justify-center gap-6">
          <Link href="/privacy" className="text-zinc-900 font-medium">Privacy</Link>
          <Link href="/terms" className="hover:text-zinc-900">Terms</Link>
          <Link href="/data" className="hover:text-zinc-900">Data Practices</Link>
        </div>
      </footer>
    </div>
  );
}
