import { SiteNav, SiteFooter, Breadcrumbs } from "@/app/components/ContentPage";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "OpenClay privacy policy. Your API key stays in browser memory, files are parsed client-side, and no personal data is collected or stored. Fully open source and verifiable.",
  alternates: { canonical: "https://openclay.io/privacy" },
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-paper text-ink">
      <SiteNav />

      <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
        <Breadcrumbs crumbs={[{ name: "Home", path: "/" }, { name: "Privacy", path: "/privacy" }]} />
        <h1 className="text-3xl font-bold">Privacy Policy</h1>
        <p className="mt-2 text-sm text-ink-2">Last updated: February 2026</p>

        <div className="mt-10 space-y-8 text-[15px] leading-relaxed text-ink-2">
          <section>
            <h2 className="text-lg font-semibold text-ink">The short version</h2>
            <p className="mt-2">
              OpenClay does not collect, store, or process any personal data. We have no database, no user accounts,
              no cookies, and no localStorage. Your API keys and spreadsheet data never leave your browser
              except to make direct API calls to your chosen AI provider (OpenAI, Google, Anthropic or xAI).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-ink">Data we collect</h2>
            <p className="mt-2">We collect minimal, anonymized usage data. Specifically:</p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5">
              <li>We do not collect personal information</li>
              <li>We do not use cookies or localStorage</li>
              <li>We do not log API requests, API keys, or user data on our servers</li>
              <li>We do not store uploaded files, they are parsed entirely in your browser</li>
              <li>We use <strong className="text-ink">Vercel Web Analytics</strong> to collect anonymous, aggregated page view data (no cookies, no personal data)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-ink">Your API key</h2>
            <p className="mt-2">
              Your API key is stored exclusively in browser memory (React <code className="rounded border border-line bg-surface-2 px-1.5 py-0.5 text-sm">useState()</code>).
              It is never written to localStorage, cookies, or any persistent storage. When you close the tab, it is gone.
              The key is sent directly from your browser to your chosen AI provider&apos;s API, our server acts only as a
              CORS proxy and does not read, log, or store the key.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-ink">Your spreadsheet data</h2>
            <p className="mt-2">
              Files are parsed entirely client-side using JavaScript libraries (PapaParse for CSV, SheetJS for Excel).
              Your data is never uploaded to any server. Enrichment results are generated by the AI provider you connect
              and returned directly to your browser.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-ink">Third-party services</h2>
            <p className="mt-2">
              When you use OpenClay, your data is sent to the AI provider you choose:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5">
              <li><strong className="text-ink">Anthropic (Claude)</strong>, subject to <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" className="text-ink underline">Anthropic&apos;s Privacy Policy</a></li>
              <li><strong className="text-ink">Google (Gemini)</strong>, subject to <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-ink underline">Google&apos;s Privacy Policy</a></li>
              <li><strong className="text-ink">Vercel Web Analytics</strong>, collects anonymous page view data without cookies. See <a href="https://vercel.com/docs/analytics/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-ink underline">Vercel Analytics Privacy</a></li>
            </ul>
            <p className="mt-3">
              This application is hosted on Vercel. Vercel may collect standard server logs (IP address, request timestamp).
              See <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-ink underline">Vercel&apos;s Privacy Policy</a> for details.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-ink">Open source</h2>
            <p className="mt-2">
              OpenClay is fully open source. You can audit the entire codebase to verify these claims. We believe
              transparency is the strongest privacy guarantee.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-ink">Contact</h2>
            <p className="mt-2">
              Questions about this policy? Reach out via{" "}
              <a href="https://www.linkedin.com/in/-raghav/" target="_blank" rel="noopener noreferrer" className="text-ink underline">LinkedIn</a>.
            </p>
          </section>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
