import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — OpenClay",
  description: "OpenClay terms of service.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-zinc-900">
      <nav className="border-b border-zinc-100 bg-white/80 backdrop-blur-xl">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-zinc-900 text-sm font-black text-white">O</div>
            <span className="text-base font-bold tracking-tight">OpenClay</span>
          </Link>
          <Link href="/tool" className="rounded-lg bg-zinc-900 px-4 py-2 text-sm font-semibold text-white transition hover:bg-zinc-800">Open App</Link>
        </div>
      </nav>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: February 2026</p>

        <div className="mt-10 space-y-8 text-[15px] leading-relaxed text-zinc-600">
          <section>
            <h2 className="text-lg font-semibold text-zinc-900">1. What OpenClay is</h2>
            <p className="mt-2">
              OpenClay is a free, open-source web application that helps users enrich spreadsheet data using AI.
              It acts as an interface between your browser and AI providers (Anthropic and Google). OpenClay does not
              provide AI services directly — it connects you to your own API key.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">2. No warranty</h2>
            <p className="mt-2">
              OpenClay is provided &quot;as-is&quot; and &quot;as-available&quot; without any warranty of any kind, express or implied.
              We make no guarantees about availability, reliability, accuracy, or fitness for a particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">3. AI-generated content</h2>
            <p className="mt-2">
              All enrichment results are generated by third-party AI models (Claude by Anthropic, Gemini by Google).
              AI-generated data may be inaccurate, incomplete, outdated, or misleading. You are solely responsible
              for verifying the accuracy of any output before using it for decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">4. Your API key and costs</h2>
            <p className="mt-2">
              You provide your own API key to use OpenClay. Any costs incurred through API usage are between you and
              your AI provider. OpenClay does not charge any fees. Cost estimates shown in the tool are approximations
              and may differ from actual charges.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">5. Your data</h2>
            <p className="mt-2">
              Your files are processed entirely in your browser. When you run enrichment, row data is sent to your
              chosen AI provider via their API. You are responsible for ensuring you have the right to process any
              data you upload and that doing so complies with applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">6. Limitation of liability</h2>
            <p className="mt-2">
              To the maximum extent permitted by law, OpenClay and its creator shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages, including but not limited to loss of data,
              loss of profits, or business interruption, arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">7. Acceptable use</h2>
            <p className="mt-2">
              You agree not to use OpenClay to process data that violates applicable laws, infringes on third-party
              rights, or violates the terms of service of your AI provider. You are responsible for your own compliance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">8. Changes</h2>
            <p className="mt-2">
              We may update these terms from time to time. Continued use of OpenClay after changes constitutes
              acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">9. Contact</h2>
            <p className="mt-2">
              Questions? Reach out via{" "}
              <a href="https://www.linkedin.com/in/-raghav/" target="_blank" rel="noopener noreferrer" className="text-zinc-900 underline">LinkedIn</a>.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-zinc-100 px-6 py-6 text-center text-xs text-zinc-400">
        <div className="mx-auto flex max-w-3xl items-center justify-center gap-6">
          <Link href="/privacy" className="hover:text-zinc-900">Privacy</Link>
          <Link href="/terms" className="text-zinc-900 font-medium">Terms</Link>
          <Link href="/data" className="hover:text-zinc-900">Data Practices</Link>
        </div>
      </footer>
    </div>
  );
}
